apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: omega-gateway
  namespace: default
spec:
  gatewayClassName: pefy-omega-traffic
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
